### ISSUE TITLE
discord bot not responding to discord input

### ISSUE THREAD

**Issue by milaTheDinosauroid** [StarryPy/StarryPy3k#144]
the bot appears to be offline, however it still prints stuff from the starbound server into the discord channel, however anything posted into the discord is NOT sent to the starbound server, additionally commands on the discord do not work

2021-10-02 14:05:11 - INFO - starrypy.plugin.discord_bot # Starting Discord Bot
2021-10-02 14:05:11 - INFO - discord.client # logging in using static token
2021-10-02 14:05:11 - INFO - discord.gateway # Created websocket connected to wss://gateway.discord.gg?encoding=json&v=6
2021-10-02 14:05:11 - INFO - discord.gateway # sent the identify payload to create the websocket
2021-10-02 14:05:12 - ERROR - starrypy.plugin.discord_bot # __new__() got an unexpected keyword argument 'deny_new'
Traceback (most recent call last):
  File "/home/server/Desktop/starry pi/StarryPy3k/plugins/discord_bot.py", line 219, in start_bot
    yield from self.connect()
  File "/home/server/.local/lib/python3.6/site-packages/discord/client.py", line 448, in connect
    yield from self.ws.poll_event()
  File "/home/server/.local/lib/python3.6/site-packages/discord/gateway.py", line 408, in poll_event
    yield from self.received_message(msg)
  File "/home/server/.local/lib/python3.6/site-packages/discord/gateway.py", line 367, in received_message
    func(data)
  File "/home/server/.local/lib/python3.6/site-packages/discord/state.py", line 509, in parse_guild_create
    server = self._get_create_server(data)
  File "/home/server/.local/lib/python3.6/site-packages/discord/state.py", line 483, in _get_create_server
    server._from_data(data)
  File "/home/server/.local/lib/python3.6/site-packages/discord/server.py", line 218, in _from_data
    self._sync(guild)
  File "/home/server/.local/lib/python3.6/site-packages/discord/server.py", line 250, in _sync
    channel = Channel(server=self, **c)
  File "/home/server/.local/lib/python3.6/site-packages/discord/channel.py", line 89, in __init__
    self._update(**kwargs)
  File "/home/server/.local/lib/python3.6/site-packages/discord/channel.py", line 116, in _update
    self._permission_overwrites.append(Overwrites(**overridden))
TypeError: __new__() got an unexpected keyword argument 'deny_new'
2021-10-02 14:05:14 - WARNING - starrypy.plugin.discord_bot # Couldn't get staff channel! Reports will be sent to the main channel.
2021-10-02 14:06:12 - DEBUG - starrypy # Initializing connection.
2021-10-02 14:06:12 - INFO - starrypy # Received connection from 192.168.0.1
2021-10-02 14:06:12 - DEBUG - starrypy # New connection established.
2021-10-02 14:06:12 - INFO - starrypy.plugin.player_manager # Known player is attempting to log in: Shurvoi
2021-10-02 14:06:12 - INFO - starrypy.plugin.basic_auth # Player with privileged UUID 'not telling you my uuid' successfully authenticated as 'mila'
2021-10-02 14:06:13 - INFO - starrypy.plugin.player_manager # Logging new planet to database.
2021-10-02 14:06:13 - INFO - starrypy.plugin.player_manager # Player Shurvoi is now at location: CelestialWorld:204757644:-657155616:29962849:7:2
2021-10-02 14:06:34 - WARNING - discord.gateway # We have stopped responding to the gateway.
2021-10-02 14:06:48 - INFO - starrypy.plugin.chat_logger # Shurvoi: test

**Comment by medeor413** [comment]
This was likely caused by Discord changing the ability to read message content into a privileged intent. The modern version should work.
