### ISSUE TITLE
Players with zero-length names cause various errors

### ISSUE THREAD

**Issue by taedixon** [StarryPy/StarryPy3k#26]
If a player joins the server with an empty string for their name, it causes problems for StarryPy. Things I've noticed so far: 

1. /list_players stops when their entry is reached
2. messages sent raise the following exception  

```2016-08-05 20:46:43 - ERROR - starrypy.plugin_manager # Exception encountered in plugin on action: c
hat_sent
Traceback (most recent call last):
  File ".\StarryPy3k\plugin_manager.py", line 45, in do if not (yield from p(packet, connection)):
  File ".\StarryPy3k\plugins\chat_enhancements.py", line 75, in on_chat_sent
    sender = self._decorate_line(connection)
  File ".\StarryPy3k\plugins\chat_enhancements.py", line 98, in _decorate_line
    connection.player.alias)
AttributeError: 'Player' object has no attribute 'alias'```

Since zero-length alias strings are (apparently) valid they should be handled gracefully.

**Comment by kharidiron** [comment]
This was handled in 1.0
