### ISSUE TITLE
Spawning items with the vanilla command throws error and failts to spawn item

### ISSUE THREAD

**Issue by ren-kun** [StarryPy/StarryPy3k#83]
Say i use the folllowing command (be it syntax correct or not) 

/spawnitem mininglantern 1 '{"beamAmbience":999999999, "beamLevel":999999999,}}' 

The following error occurs 
-------------------------
Traceback (most recent call last): 
onmessage   File "server.py", line 136, in send_message 
onmessage     yield from self.raw_write(to_send) 
onmessage   File "server.py", line 144, in raw_write 
onmessage     yield from self._writer.drain() 
onmessage   File "/usr/lib/python3.5/asyncio/streams.py", line 333, in drain 
onmessage     yield from self._protocol._drain_helper() 
onmessage   File "/usr/lib/python3.5/asyncio/streams.py", line 208, in _drain_helper 
onmessage     assert waiter is None or waiter.cancelled() 
onmessage AssertionError 
onmessage 2017-05-19 02:47:14 - ERROR - starrypy #  
onmessage Traceback (most recent call last): 
onmessage   File "server.py", line 136, in send_message 
onmessage     yield from self.raw_write(to_send) 
onmessage   File "server.py", line 144, in raw_write 
onmessage     yield from self._writer.drain() 
onmessage   File "/usr/lib/python3.5/asyncio/streams.py", line 333, in drain 
onmessage     yield from self._protocol._drain_helper() 
onmessage   File "/usr/lib/python3.5/asyncio/streams.py", line 208, in _drain_helper 
onmessage     assert waite

**Comment by GermaniumSystem** [comment]
This happens every time you try to use that command?

I'm unable to replicate the issue on the latest version (7d939f0) or on my production server.

**Comment by ren-kun** [comment]
I will update and try again soon
