### ISSUE TITLE
Parder error

### ISSUE THREAD

**Issue by ren-kun** [StarryPy/StarryPy3k#89]
2017-06-09 00:29:09 - ERROR - starrypy.plugin_manager # Exception encountered in plugin on action: player_warp_result
Traceback (most recent call last):
  File "/var/Server/Starbound/Starbound/wrapper/StarryPy3k-master/plugin_manager.py", line 45, in do
    if not (yield from p(packet, connection)):
  File "/var/Server/Starbound/Starbound/wrapper/StarryPy3k-master/plugins/player_manager.py", line 351, in on_player_warp_result
    if data["parsed"]["warp_success"]:
KeyError: 'parsed'

**Comment by medeor413** [comment]
Can you check and see if this was fixed in [the latest commit?](https://github.com/StarryPy/StarryPy3k/commit/05e5859f2e3512fd6afa78ecaeabeec9ed5d1ab5)

**Comment by kharidiron** [comment]
Agreed. This is a bug that was fixed in the most recent commit. Just pull the latest.
