### ISSUE TITLE
AssertionError 

### ISSUE THREAD

**Issue by ren-kun** [StarryPy/StarryPy3k#93]
Error that pops up here and there. 

> 
> Traceback (most recent call last): 
> onmessage  File "server.py", line 136, in send_message 
> onmessage    yield from self.raw_write(to_send) 
> onmessage  File "server.py", line 144, in raw_write 
> onmessage    yield from self._writer.drain() 
> onmessage  File "/usr/lib/python3.5/asyncio/streams.py", line 333, in drain 
> onmessage    yield from self._protocol._drain_helper() 
> onmessage  File "/usr/lib/python3.5/asyncio/streams.py", line 208, in _drain_helper 
> onmessage    assert waiter is None or waiter.cancelled() 
> onmessageAssertionError 
> onmessage2017-06-11 02:19:42 - ERROR - starrypy #  
> onmessageTraceback (most recent call last): 
> onmessage  File "server.py", line 136, in send_message 
> onmessage    yield from self.raw_write(to_send) 
> onmessage  File "server.py", line 144, in raw_write 
> onmessage    yield from self._writer.drain() 
> onmessage  File "/usr/lib/python3.5/asyncio/streams.py", line 333, in drain 
> onmessage    yield from self._protocol._drain_helper() 
> onmessage  File "/usr/lib/python3.5/asyncio/streams.py", line 208, in _drain_helper 
> onmessage    assert waiter is None or waiter.cancelled() 
> onmessageAssertionError

**Comment by ren-kun** [comment]
> Traceback (most recent call last): 
> onmessage
>   File "/var/Server/Starbound/Starbound/wrapper/StarryPy3k-master/plugin_manager.py", line 45, in do 
> onmessage
>     if not (yield from p(packet, connection)): 
> onmessage
>   File "/var/Server/Starbound/Starbound/wrapper/StarryPy3k-master/plugins/player_manager.py", line 377, in on_player_warp_result 
> onmessage
>     warp_data["ship_id"]) 
> onmessage
>   File "/usr/lib/python3.5/asyncio/coroutines.py", line 210, in coro 
> onmessage
>     res = func(*args, **kw) 
> onmessage
>   File "/var/Server/Starbound/Starbound/wrapper/StarryPy3k-master/plugins/player_manager.py", line 847, in _add_or_get_ship 
> onmessage
>     ship = Ship(uuid, _get_player_name(uuid)) 
> onmessage
>   File "/var/Server/Starbound/Starbound/wrapper/StarryPy3k-master/plugins/player_manager.py", line 840, in _get_player_name 
> onmessage
>     if p.player.uuid == uid: 
> onmessage
> AttributeError: 'StarryPyServer' object has no attribute 'player' 
> onmessage
> 2017-06-12 01:01:19 - INFO - starrypy.plugin.player_manager # Player Cellestiass is now at location: InstanceWorld:outpost:- 
> onmessage
> 2017-06-12 01:01:24 - ERROR - starrypy.plugin_manager # Exception encountered in plugin on action: player_warp_result 
> onmessage
> Traceback (most recent call last): 
> onmessage
>   File "/var/Server/Starbound/Starbound/wrapper/StarryPy3k-master/plugin_manager.py", line 45, in do 
> onmessage
>     if not (yield from p(packet, connection)): 
> onmessage
>   File "/var/Server/Starbound/Starbound/wrapper/StarryPy3k-master/plugins/player_manager.py", line 362, in on_player_warp_result 
> onmessage
>     p.location = yield from self._add_or_get_ship(p.uuid) 
> onmessage
>   File "/usr/lib/python3.5/asyncio/coroutines.py", line 210, in coro 
> onmessage
>     res = func(*args, **kw) 
> onmessage
>   File "/var/Server/Starbound/Starbound/wrapper/StarryPy3k-master/plugins/player_manager.py", line 847, in _add_or_get_ship 
> onmessage
>     ship = Ship(uuid, _get_player_name(uuid)) 
> onmessage
>   File "/var/Server/Starbound/Starbound/wrapper/StarryPy3k-master/plugins/player_manager.py", line 840, in _get_player_name 
> onmessage
>     if p.player.uuid == uid: 
> onmessage
> AttributeError: 'StarryPyServer' object has no attribute 'player'

**Comment by ren-kun** [comment]
onmessage Traceback (most recent call last): 
onmessage   File "/var/Server/Starbound/Starbound/wrapper/StarryPy3k-master/plugin_manager.py", line 45, in do 
onmessage     if not (yield from p(packet, connection)): 
onmessage   File "/var/Server/Starbound/Starbound/wrapper/StarryPy3k-master/plugins/player_manager.py", line 377, in on_player_warp_result 
onmessage     warp_data["ship_id"]) 
onmessage   File "/usr/lib/python3.5/asyncio/coroutines.py", line 210, in coro 
onmessage     res = func(*args, **kw) 
onmessage   File "/var/Server/Starbound/Starbound/wrapper/StarryPy3k-master/plugins/player_manager.py", line 847, in _add_or_get_ship 
onmessage     ship = Ship(uuid, _get_player_name(uuid)) 
onmessage   File "/var/Server/Starbound/Starbound/wrapper/StarryPy3k-master/plugins/player_manager.py", line 840, in _get_player_name 
onmessage     if p.player.uuid == uid: 
onmessage AttributeError: 'StarryPyServer' object has no attribute 'player'

**Comment by medeor413** [comment]
The causes of the second and third errors will be fixed in the next pull, but I'm not sure what the first error is trying to say. See if you can reproduce it with more information?

**Comment by medeor413** [comment]
Further testing tells me that the AssertionError above is happening when a plugin tries to send a packet to a disconnected player. I'll look into fixing that.
